version: 2.1
jobs:
#  clear-cache:
#    steps:
#      - checkout
#      - run:
#          name: "Jest: Clear cache"
#          command: "yarn test:clearCache"

  all-tests:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: "Test env var"
          command: "echo $PORT"
      - run:
          name: "Install packages"
          command: "yarn install"
      - run:
          name: "Run tests"
          command: "yarn test"

workflows:
  all-tests-workflow:
    jobs:
#      - clear-cache
      - all-tests:
          context: sos-tag-api
