name: Lint

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
      env:
        PORT: ${{ secrets.PORT }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
        SMTP_SERVICE: ${{ secrets.SMTP_SERVICE }}
        GOOGLE_CLIENT_USER: ${{ secrets.GOOGLE_CLIENT_USER }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        GOOGLE_CLIENT_REFRESH_TOKEN: ${{ secrets.GOOGLE_CLIENT_REFRESH_TOKEN }}
        GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}
        GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
        GOOGLE_OAUTH_REDIRECT_URL: ${{ secrets.GOOGLE_OAUTH_REDIRECT_URL }}
        WEB_APP_GOOGLE_AUTH_URL: ${{ secrets.WEB_APP_GOOGLE_AUTH_URL }}
    - run: yarn install
    - run: yarn lint
